#!/bin/sh

logger -p notice -t "hotplug.d" "60-wan: run because of $INTERFACE $ACTION"

[ "$ACTION" = "ifup" ] && [ "$INTERFACE" = "wan" ] && {
    . /lib/network/config.sh
    [ -f /usr/sbin/smartdns.lua ] && /usr/bin/lua /usr/sbin/smartdns.lua &
    ubus_call network.interface.wan status
    json_select "route"
    __idx=1
    while json_is_a "$__idx" object; do
        json_select "$((__idx++))"
        json_get_var target "target"
        json_get_var mask "mask"
        json_get_var nexthop "nexthop"
        route add -net $target/$mask gw $nexthop metric 50
        json_select ".."
    done
}

mode=$(uci -q get ipv6.settings.mode)

[ "$INTERFACE" = "wan_6" -a "$mode" = "static" ] && {
	wan6_old=$(ip -6 route | grep "default via" | awk 'NR==1 {print $3}')

	if [ "$ACTION" == "ifup" ]; then
		wan6_cfg=$(uci -q get ipv6.settings.ip6gw)
		if [ -n "$wan6_old" -a "$wan6_cfg" != "$wan6_old" ]; then
		    ip -6 route del default via $wan6_old
		fi
		ip -6 route add default via $wan6_cfg
	elif [ "$ACTION" == "ifdown" -a -n $wan6_old ]; then
		ip -6 route del default via $wan6_old
	fi
}

[ "$INTERFACE" = "wan_6" ] && [ "$mode" = "native" -o "$mode" = "nat" ] && {
	#flush all deprecated address
    ip -6 address flush scope global deprecated dynamic

	res=$(ip -6 route | grep "default from")
	wan6_gw=$(echo $res | awk 'NR==1 {print $5}')
	wan6_itf=$(echo $res | awk 'NR==1 {print $7}')
	[ -z "$wan6_gw" -o -z "$wan6_itf" ] && return

	wan6_old=$(ip -6 route | grep "default via" | awk 'NR==1 {print $3}')
	if [ "$ACTION" == "ifup" ]; then
		[ -n "$wan6_old" ] && ip -6 route del default via $wan6_old
		        ip -6 route add default via $wan6_gw dev $wan6_itf
	elif [ "$ACTION" == "ifupdate" ]; then
                ip -6 route change default via $wan6_gw dev $wan6_itf
	elif [ "$ACTION" == "ifdown" -a -n $wan6_old ]; then
		ip -6 route del default via $wan6_old
	fi
}