#!/bin/sh

ap_mode=$(uci -q get xiaoqiang.common.NETMODE)
if [ "$ap_mode" = "lanapmode" -o "$ap_mode" = "wifiapmode" -o "$ap_mode" = "whc_re" ]; then
	return 0
fi
		
[ "$ACTION" = "ifup" ] && [ "$INTERFACE" = "lan" ] && {
    if [ -x /usr/sbin/ipaccount ]; then
        ipaddr=$(uci get network.lan.ipaddr)
        netmask=$(uci get network.lan.netmask)
        /usr/sbin/ipaccount -S -n lan -N "$ipaddr/$netmask"
    fi
}

[ "$INTERFACE" = "guest" ] && {
    if [ -x /usr/sbin/ipaccount ]; then
        ipaddr=$(uci get network.guest.ipaddr)
        netmask=$(uci get network.guest.netmask)
        [ "$ACTION" = "ifup" ] && /usr/sbin/ipaccount -S -n guest -N "$ipaddr/$netmask"
#        [ "$ACTION" = "ifdown" ] && /usr/sbin/ipaccount -D -n guest
    fi
}

[ "$ACTION" = "ifup" ] && {
    /usr/sbin/ipaccount -r
}
