#!/bin/sh /etc/rc.common
#
# Copyright (c) 2017 Qualcomm Technologies, Inc.
#
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.

START=42

start_diag_app()
{
	local serverip=`nvram get serverip`
	
	if [ -n "$serverip" ]; then
	/usr/sbin/diag_socket_app -a $serverip &
	else
	/usr/sbin/diag_socket_app -a 192.168.31.100 &
	fi
	echo "/usr/sbin/diag_socket_app started" > /dev/kmsg
}

start() {
	is_ftm=`cat /proc/xiaoqiang/ft_mode`
	[ $is_ftm = 1 ] && start_diag_app
}

