#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
NAME=meshd
PROG=/usr/sbin/meshd

start_service() {
	local init_flag=$(uci -q get xiaoqiang.common.INITTED)
	local mac=$(uci -q get wireless.wifi0.macaddr)
	if [ "$init_flag" != "YES" ]; then
		procd_open_instance
		procd_set_param command "$PROG" -i wl0 -t 10 -a $mac
		procd_set_param respawn
		procd_close_instance
	fi
}
