#!/bin/sh /etc/rc.common
# Basic init script for mosquitto
# April 2012, OpenWrt.org
# Provides support for the luci-app-mosquitto package, if installed

START=90
USE_PROCD=1
CONF=/etc/mosquitto/mosquitto.conf

start_service() {
    #only work for CAP mode
    ap_mode=$(uci -q get xiaoqiang.common.NETMODE)
    [ "$ap_mode" != "whc_cap" ] && return 0

    [ -f "/usr/sbin/mqautogen.lua" ] && lua /usr/sbin/mqautogen.lua

	procd_open_instance
	procd_set_param command mosquitto
	procd_append_param command -c $CONF
	procd_set_param respawn
	# Makes /etc/init.d/mosquitto reload work if you edit the final file.
	procd_set_param file $CONF
	procd_close_instance
}

service_triggers() {
	# Makes "reload_config" work
	procd_add_reload_trigger "mosquitto"
}
