#!/bin/sh /etc/rc.common

START=97
STOP=20

USE_PROCD=1
PROG=/usr/sbin/plugincenter

start_service() {

	#删除记录插件pid的文件
	rm /userdisk/appdata/plugin_id_info.cfg -f

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
}
