#!/bin/sh /etc/rc.common
#
# Copyright (c) 2014-2015 The Linux Foundation. All rights reserved.
# Permission to use, copy, modify, and/or distribute this software for
# any purpose with or without fee is hereby granted, provided that the
# above copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT
# OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

#SFE connection manager has a lower priority, it should be started after other connection manager
#to detect the existence of connection manager with higher priority
#START=72

have_cm() {
	[ -d "/sys/kernel/debug/ecm" ] && echo 1 && return
	[ -d "/sys/module/shortcut_fe_cm" ] && echo 1 && return

	local vpn_up=$(ubus call network.interface.vpn status 2>/dev/null | grep -Eq '"up": true' && echo 1 || echo 0)
	[ "$vpn_up" == "1" ] && {
		stop
		echo 1 && return
	}

	local ipv6_enabled=$(uci -q get ipv6.settings.enabled)
	local ipv6_mode=$(uci -q get ipv6.settings.mode)
	[ "$ipv6_enabled" == "1" -a "$ipv6_mode" == "nat" ] && {
		stop
		echo 1 && return
	}

	echo 0
}

#load shortcut-fe connection manager
load_sfe_cm() {
	local kernel_version=$(uname -r)

	#shortcut-fe-drv.ko is not needed because other connection manager is not enabled
	[ -d /sys/module/shortcut_fe_drv ] && rmmod shortcut_fe_drv
	[ -d /sys/module/shortcut_fe ] || insmod /lib/modules/$kernel_version/shortcut-fe
	[ -d /sys/module/shortcut_fe_ipv6 ] || insmod /lib/modules/$kernel_version/shortcut-fe-ipv6
	
	[ -e "/lib/modules/$kernel_version/shortcut-fe-cm.ko" ] && {
		[ -d /sys/module/shortcut_fe_cm ] || insmod /lib/modules/$kernel_version/shortcut-fe-cm.ko
	}
	[ -e "/lib/modules/$kernel_version/fast-classifier.ko" ] && {
		[ -d /sys/module/fast_classifier ] || insmod /lib/modules/$kernel_version/fast-classifier.ko
	}
}

start() {
	[ "$(have_cm)" = "1" ] || load_sfe_cm
}

stop() {
	[ -d /sys/module/shortcut_fe_drv ] && rmmod shortcut_fe_drv
	[ -d /sys/module/shortcut_fe_cm ] && rmmod shortcut_fe_cm
	[ -d /sys/module/fast_classifier ] && rmmod fast_classifier
	[ -d /sys/module/shortcut_fe ] && rmmod shortcut-fe
	[ -d /sys/module/shortcut_fe_ipv6 ] && rmmod shortcut-fe-ipv6
}
