#!/bin/sh /etc/rc.common

#for test, activate later
START=77

NAME=trafficd
USE_PROCD=1
CMD="/usr/sbin/trafficd"
PROC_FILE="/proc/sys/net/ipv4/ipaccount/if_mapping"

init_dev() {
    #check ifname mapping 1stly
    [ -f "$PROC_FILE" ] || return 0

    #lan dev
    if_lan=$(uci -q get network.lan.ifname)
    [ -z "$if_lan" ] && if_lan="eth0"
    #get parent-ifname only
    if_lan=${if_lan%%.*}

    #5G dev
    if_wl_5g=$(uci -q get misc.wireless.ifname_5G)
    [ -z "$if_wl_5g" ] && if_wl_5g="wl0"

    #2.4G
    if_wl_2g=$(uci -q get misc.wireless.ifname_2G)
    [ -z "$if_wl_2g" ] && if_wl_2g="wl1"

    #guest 2g
    if_wl_guest=$(uci -q get misc.wireless.ifname_guest_2G)
    [ -z "$if_wl_guest" ] && if_wl_guest="wl3"

    #5G backhaul
    if_wl_5g_backhaul=$(uci -q get misc.backhauls.backhaul_5g_ap_iface)
    [ -z "$if_wl_5g_backhaul" ] && if_wl_5g_backhaul="wl5"

    echo "refresh ifname into ipaacount in [lan-dev 5g-wl 2.4g-wl wl-guest 5g-wl-backhaul]"
    echo "$if_lan $if_wl_5g $if_wl_2g $if_wl_guest $if_wl_5g_backhaul"

    # set lan dev of D01
    hardware=$(uci -q get misc.hardware.model)
    if [ "$hardware" == "D01" ]; then
        if_lan="eth1 eth2 eth3"
    fi

    echo "$if_lan $if_wl_5g $if_wl_2g $if_wl_guest $if_wl_5g_backhaul" >"$PROC_FILE"

    return 0
}

start_service() {
	init_dev
	ap_mode=$(uci -q get xiaoqiang.common.NETMODE)
	if [ "$ap_mode" = "lanapmode" -o "$ap_mode" = "wifiapmode" -o "$ap_mode" = "whc_re" ]; then
		return 0
	fi
	procd_open_instance
	procd_set_param command ${CMD}
	procd_set_param respawn
	procd_close_instance
	echo "trafficd start ok"
}

stop() {
    service_stop ${CMD}
}

reload() {
    service_reload ${CMD}
}
