#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=98
NAME=wancheck
USE_PROCD=1
PROG=/usr/sbin/check_wan_status.lua


start_service(){
    [ -f "$PROG" ] && {
	procd_open_instance
	procd_set_param command "/usr/bin/lua" "$PROG"
	procd_set_param respawn
	procd_close_instance
    }
}