#!/bin/sh /etc/rc.common

START=98

USE_PROCD=1
PROG=/usr/bin/wrsst

start_service() {
	# start command
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
	echo "start wrsst ok."
}

