#!/bin/sh /etc/rc.common

START=13

USE_PROCD=1
NAME=xiaoqiang_sync
PROG=/usr/sbin/xiaoqiang_sync

start_service() {
	mode=$(uci -q get xiaoqiang.common.NETMODE)
	[ "x$ap_mode" == "x" ] && return 0
        procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
}

stop_service() {
	service_stop ${PROG}
}

restart_service() {
	service_reload ${PROG}
}
