#!/bin/sh /etc/rc.common

START=98
#STOP=99

USE_PROCD=1
PROG=/usr/sbin/xiaoqiang_sync.lua

start_service() {
	local netmode
	netmode=`uci -q -S get xiaoqiang.common.NETMODE`
	if [ "$netmode" = "wifiapmode" -o "$netmode" = "lanapmode" -o "$netmode" = "whc_re" ]; then
	    [ -f "$PROG" ] && {
		procd_open_instance
		procd_set_param command "$PROG"
		procd_set_param respawn
		procd_close_instance
	    }
    fi
}

#
