#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
NAME=xq_info_sync_mqtt
PROG=/usr/sbin/xq_info_sync_mqtt

# parse json code
parse_json()
{
	# {"code":0,"data":{"bind":1,"admin":499744955}}
	echo "$1" | awk -F "$2" '{print$2}'|awk -F "" '{print $3}'
}

check_my_bind_status()
{
	local bind_status=$(timeout -t 5 matool --method api_call --params "/device/minet_get_bindinfo" 2>/dev/null)
	if [ $? -ne 0 ];
	then
		echo "[matool --method minet_get_bindinfo] error!"
		return 2
	fi
	# {"code":0,"data":{"bind":1,"admin":499744955}}
	local code=$(parse_json $bind_status "code")
	if [ -n "$code" ] && [ $code -eq 0 ]; then
		#bind_log "code: $code"
		local bind=$(parse_json $bind_status "bind")
		return $bind
	else
		return 0
	fi
}

start_service() {
	ap_mode=$(uci -q get xiaoqiang.common.NETMODE)
	if [ "$ap_mode" != "whc_cap" -a "$ap_mode" != "whc_re" ]; then
		return 0
	fi
	status=$(uci -q get bind.info.status)
	if [ "$status" -eq 0 ]; then
		check_my_bind_status
		if [ $? -eq 1 ]; then
			uci set bind.info.status='1'
			uci set bind.info.record='1'
			uci commit bind
		fi
	fi
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
}
