#!/bin/sh /etc/rc.common

START=98
#STOP=99

USE_PROCD=1
PROG=/usr/sbin/xqbc

start_service() {
	local wifimode
	netmode=`uci -q -S get xiaoqiang.common.NETMODE`
	if [ "$netmode" = "wifiapmode" -o "$netmode" = "lanapmode" ]; then
    		[ -f "$PROG" ] && {
    		procd_open_instance
    		procd_set_param command "$PROG" 988
    		procd_set_param respawn
    		procd_close_instance
    		}
    	fi
}

#
