#!/bin/sh /etc/rc.common                                                                                                                                                     

# should load after repacd
START=98
#STOP=70
#CMD="ash /usr/sbin/xqwhc_superv"
CMD="/usr/sbin/xqwhc_superv"
USE_PROCD=1
PROCD_DEBUG=1

# trace caller
ppid=$PPID
logger -p user.info -t "xqwhc_superv" "$1**ppid=$ppid, cmd=<`cat /proc/${ppid}/cmdline`>"

start_service() {
	[ "1" = "`cat /proc/xiaoqiang/ft_mode 2>/dev/null`" ] && {
		echo "xqwhc *** in FT mode, skip handle "
		return 0
	}
	mode="`uci -q get xiaoqiang.common.NETMODE`"
	[ "$mode" = "whc_cap" -o "$mode" = "whc_re" ] || {
		echo "xqwhc *** not in cap/re mode, skip handle "
		return 0
	}

	procd_open_instance
	procd_set_param command ${CMD}
	procd_set_param respawn
	procd_close_instance
	return 0
}

stop() {
	service_stop ${CMD}
}

reload() {
	service_reload ${CMD}
}

