#!/bin/sh
PPP_IPPARAM="$6"

. /lib/netifd/netifd-proto.sh
proto_init_update "$IFNAME" 1 1
proto_set_keep 1
[ -n "$PPP_IPPARAM" ] && {
	[ -n "$LLLOCAL" ] && proto_add_ipv6_address "$LLLOCAL" 128
}
proto_send_update "$PPP_IPPARAM"

[ -d /etc/ppp/ip-up.d ] && {
	for SCRIPT in /etc/ppp/ip-up.d/*
	do
		[ -x "$SCRIPT" ] && "$SCRIPT" "$@"
	done
}

if [ -n "$AUTOIPV6" ]; then
	ip6_mode=$(uci -q get ipv6.settings.mode)
	[ -z $ip6_mode -o "$ip6_mode" = "off" ] && return
	[ "$ip6_mode" = "static" ] && {
		ip6_addr=$(uci -q get ipv6.settings.ip6addr)
		ip6_gw=$(uci -q get ipv6.settings.ip6gw)
		[ -z $ip6_addr -o -z $ip6_gw ] && return
	}
	ZONE=$(fw3 -q network $PPP_IPPARAM 2>/dev/null)

	json_init
	json_add_string name "${PPP_IPPARAM}_6"
	json_add_string ifname "@$PPP_IPPARAM"
	if [ "$ip6_mode" = "static" ]; then
		json_add_string proto "static"
		_proto_push_array "ip6addr" $ip6_addr _proto_push_string
		json_add_string ip6gw "$ip6_gw"
	else
		json_add_string proto "dhcpv6"
		[ -n "$EXTENDPREFIX" ] && json_add_string extendprefix 1
		[ -n "$IP6TABLE" ] && json_add_string ip6table $IP6TABLE
	fi
	[ -n "$ZONE" ] && json_add_string zone "$ZONE"
#	[ -n "$PEERDNS" ] && json_add_boolean peerdns $PEERDNS
	peerdns=$(uci -q get ipv6.dns.peerdns)
	json_add_boolean peerdns $peerdns
    if [ "$peerdns" == "0" ]; then
		proto_init_dns_server_ex
		dnslist=$(uci -q get ipv6.dns.dns)
		var=${dnslist//,/ }
		for dns in $var; do
            proto_add_dns_server_ex $dns
		done
		proto_update_dns_server_ex
	fi

	json_close_object
	ubus call network add_dynamic "$(json_dump)"
fi
